logging:
  level:
    ROOT: INFO
    com.banvien.infofabrica.sdx.auth: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/shopping
    username: shopping
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.default_schema: shopping
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: shopping
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.naming.implicit-strategy: org.hibernate.cfg.EJB3NamingStrategy
server:
  servlet:
    context-path: /shopping
  port: 4000